### PR TITLE
Fix `gdk-keymap-get-entries-for-keycode`.

### PR DESCRIPTION
**Pull request by Ferada**
https://github.com/crategus/cl-cffi-gtk/issues/60

### CODE REVIEW

**Comment by Ferada** [comment]
@stacksmith does that look about right? I'd test it later today.

**Review by stacksmith — APPROVED** [review]
That's what I have... I've used it in a couple of tests.

**Comment by stacksmith** [comment]
I am still trying to figure out the best workflow...  I want you to have the fixes, but having started with the Crategus codebase, I feel that I should create issues there...  This is a bit of a mess.

**Comment by Ferada** [comment]
Of course yes, don't worry about managing the issue here.

**Comment by Ferada** [comment]
wfm

**Pull request merged**
